maize_navigation:
  ros__parameters:
    x_min_drive_in_row: -0.2
    x_max_drive_in_row: 1.15
    y_min_drive_in_row: 0.1
    y_max_drive_in_row: 0.75

    x_min_turn_and_exit: -1.0
    x_max_turn_and_exit: 1.0
    y_min_turn_and_exit: 0.1
    y_max_turn_and_exit: 1.5

    x_min_counting_rows: 0.2435
    x_max_counting_rows: 0.5935
    y_min_counting_rows: 0.2
    y_max_counting_rows: 1.75

    x_min_turn_to_row: 0.1
    x_max_turn_to_row: 1.5
    y_min_turn_to_row: 0.0
    y_max_turn_to_row: 0.75

    x_min_turn_to_row_critic: 0.1
    x_max_turn_to_row_critic: 1.5
    y_min_turn_to_row_critic: 0.0
    y_max_turn_to_row_critic: 0.75

    both_sides: 'both'
    box: 'drive'

    pattern_steps:
      - 3
      - 1
      - 1
      - 1
      - 1
      - 1

    pattern_directions:
      - 'L'
      - 'R'
      - 'L'
      - 'R'
      - 'L'
      - 'R'


    critic_row: [2,5]

    vel_linear_turn: 0.25
    vel_linear_drive: 0.7
    vel_linear_count: 0.25
    row_width: 0.75
    drive_out_dist: 0.5315
    max_dist_in_row: 0.15

    # Kommentare sind erlaubt, aber achten Sie darauf, dass sie keine Datenstruktur beeinflussen.
    # Beispiel: Die folgenden Werte sind kommentiert und werden nicht geladen:
    # laserdist = 0.3315 rowdist + 0.4 = 0.6315
    # static tf auf base node
    # use full sensorscan
    # other plants?
    # radar?
    # neighbour rows

visu:
  ros__parameters:
    x_min_drive_in_row: -0.2
    x_max_drive_in_row: 1.15
    y_min_drive_in_row: 0.1
    y_max_drive_in_row: 0.75

    x_min_turn_and_exit: -1.0
    x_max_turn_and_exit: 1.0
    y_min_turn_and_exit: 0.1
    y_max_turn_and_exit: 1.5

    x_min_counting_rows: 0.2435
    x_max_counting_rows: 0.5935
    y_min_counting_rows: 0.2
    y_max_counting_rows: 1.75

    x_min_turn_to_row: 0.1
    x_max_turn_to_row: 1.5
    y_min_turn_to_row: 0.0
    y_max_turn_to_row: 0.75

    x_min_turn_to_row_critic: 0.1
    x_max_turn_to_row_critic: 1.5
    y_min_turn_to_row_critic: 0.0
    y_max_turn_to_row_critic: 0.75

    both_sides: 'both'
    box: 'drive'

    pattern_steps:
      - 3
      - 1
      - 1
      - 1
      - 1
      - 1

    pattern_directions:
      - 'L'
      - 'R'
      - 'L'
      - 'R'
      - 'L'
      - 'R'


    critic_row: [2,5]

    vel_linear_turn: 0.25
    vel_linear_drive: 0.7
    vel_linear_count: 0.25
    row_width: 0.75
    drive_out_dist: 0.5315
    max_dist_in_row: 0.15

    # Kommentare sind erlaubt, aber achten Sie darauf, dass sie keine Datenstruktur beeinflussen.
    # Beispiel: Die folgenden Werte sind kommentiert und werden nicht geladen:
    # laserdist = 0.3315 rowdist + 0.4 = 0.6315
    # static tf auf base node
    # use full sensorscan
    # other plants?
    # radar?
    # neighbour rows
