# The joint state controller handles publishing transforms for any moving joints
controller_manager:
   ros__parameterss:
      update_rate: 10  # Hz
      use_sim_time: True

      joint_broad:
         type: joint_state_broadcaster/JointStateBroadcaster

      joint_fl_controller:
         type: velocity_controllers/JointVelocityController

      joint_fr_controller:
         type: velocity_controllers/JointVelocityController

      joint_rl_controller:
         type: velocity_controllers/JointVelocityController

      joint_rr_controller:
         type: velocity_controllers/JointVelocityController

      body_angle_controller:
         type: velocity_controllers/JointVelocityController

      swing_angle_controller:
         type: velocity_controllers/JointVelocityController


joint_fl_controller:
   ros__parameters:
      joint: joint_frontLeft
      interface_name: position
      command_interface: velocity
      state_interface: velocity
      state_interface: position
      pid: {p: 5.0, i: 0, d: 0}

joint_fr_controller:
   ros__parameters:
      joint: joint_frontRight
      interface_name: position
      command_interface: velocity
      state_interface: velocity
      state_interface: position
      pid: {p: 5.0, i: 0, d: 0}

joint_rl_controller:
   ros__parameters:
      joint: joint_rearLeft
      interface_name: position
      command_interface: velocity
      state_interface: velocity
      state_interface: position
      pid: {p: 5.0, i: 0, d: 0}

joint_rr_controller:
   ros__parameters:
      joint: joint_rearRight
      interface_name: position
      command_interface: velocity
      state_interface: velocity
      state_interface: position
      pid: {p: 5.0, i: 0, d: 0}
